import Head from "next/head";
import Section from "../components/section";

import Activities from "../features/activities";

export default function Activity() {
  return (
    <>
      <Head>
        <title>Activity</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Section>
        <Activities />
      </Section>
    </>
  );
}
