import { useEffect } from "react";
import Head from "next/head";
import { useRouter } from "next/router";

import s from "../styles/Splash.module.css";
import u from "../styles/Utility.module.css";
import LandingScene from "../modules/landing-page";

const DURATION = 1000 * 3;

export default function Home() {
  const router = useRouter();

  useEffect(() => {
    const timer = setTimeout(() => {
      router.push("/sign-up");
    }, DURATION);
    return () => clearTimeout(timer);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div className={u.lApp}>
      <Head>
        <title>Flowt</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={s.lMain}>
        <LandingScene />
      </main>
    </div>
  );
}
