import Head from "next/head";
import { useState } from "react";
import Image from "next/image";
import { PaystackButton } from "react-paystack";
import styles from "../styles/Home.module.css";

const publicKey = process.env.NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY;

export default function Home() {
  const amount = 100; // Remember, set in kobo!
  const [email, setEmail] = useState("");
  const [name, setName] = useState("");
  const [phone, setPhone] = useState("");

  const componentProps = {
    email,
    amount,
    metadata: {
      name,
      phone,
    },
    publicKey,
    currency: "zar",
    text: "Pay Now",
    onSuccess: () =>
      alert("Thanks for doing business with us! Come back soon!!"),
    onClose: () => alert("Wait! Don't leave :("),
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="App">
          <div className="container">
            <div className="item">
              <div className="overlay-effect"></div>
              <Image
                className="item-image"
                src="https://images.unsplash.com/photo-1526947425960-945c6e72858f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2850&q=80"
                alt="product"
                width="100px"
                height="100px"
              />
              <div className="item-details">
                <p className="item-details__title">Coconut Oil</p>
                <p className="item-details__amount">NGN{amount / 100}</p>
              </div>
            </div>
            <div className="checkout">
              <div className="checkout-form">
                <div className="checkout-field">
                  <label>Name</label>
                  <input
                    type="text"
                    id="name"
                    onChange={(e) => setName(e.target.value)}
                    value={name}
                  />
                </div>
                <div className="checkout-field">
                  <label>Email</label>
                  <input
                    type="text"
                    id="email"
                    onChange={(e) => setEmail(e.target.value)}
                    value={email}
                  />
                </div>
                <div className="checkout-field">
                  <label>Phone</label>
                  <input
                    type="text"
                    id="phone"
                    onChange={(e) => setPhone(e.target.value)}
                    value={phone}
                  />
                </div>
                <PaystackButton
                  className="custom-checkout"
                  {...componentProps}
                />
              </div>
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
